### ISSUE TITLE
Select-able content

### ISSUE THREAD

**Issue by MidasXIV** [JessicaLim8/jessicalim8.github.io#2]
![captured (9)](https://user-images.githubusercontent.com/24829816/88544213-1a7fac00-d02a-11ea-8709-1c0864ac0083.gif)

try adding the following class to your 2 section elements to make the text non selectable;

```CSS
.unselectable {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
